# Generated by Django 5.0.1 on 2024-02-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='transaction_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='stockupdate',
            name='update_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
